import { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import { getCurrentUser } from 'aws-amplify/auth'
import { generateClient } from 'aws-amplify/data'
import type { Schema } from '../../amplify/data/resource'
import Layout from '../components/Layout'
import { seedDatabase, deleteAllData } from '../utils/seedData'
import './Profile.css'

// Schema will be generated by Amplify sandbox
const client = generateClient<Schema>()

export default function Profile() {
    const [user, setUser] = useState<any>(null)
    const [profile, setProfile] = useState<any>(null)
    const [loading, setLoading] = useState(true)
    const [deleting, setDeleting] = useState(false)
    const [editing, setEditing] = useState(false)
    const [formData, setFormData] = useState({
        displayName: '',
        bio: '',
    })

    useEffect(() => {
        loadProfile()
    }, [])

    const loadProfile = async () => {
        try {
            const currentUser = await getCurrentUser()
            setUser(currentUser)

            // Try to load user profile from database
            const { data: profiles } = await client.models.UserProfile.list({
                filter: { email: { eq: currentUser.signInDetails?.loginId || '' } }
            })

            if (profiles.length > 0) {
                setProfile(profiles[0])
                setFormData({
                    displayName: profiles[0].displayName || '',
                    bio: profiles[0].bio || '',
                })
            }
        } catch (error) {
            console.error('Error loading profile:', error)
        } finally {
            setLoading(false)
        }
    }

    const handleSave = async () => {
        try {
            if (profile) {
                // Update existing profile
                await client.models.UserProfile.update({
                    id: profile.id,
                    ...formData,
                })
            } else {
                // Create new profile
                await client.models.UserProfile.create({
                    username: user.username,
                    email: user.signInDetails?.loginId || '',
                    ...formData,
                })
            }

            await loadProfile()
            setEditing(false)
        } catch (error) {
            console.error('Error saving profile:', error)
        }
    }

    const handleSeedData = async () => {
        if (!window.confirm('This will create sample data (Assets, Groups, Tasks, etc.). Continue?')) return

        setLoading(true)
        try {
            await seedDatabase(client)
            alert('Data generated successfully! Navigate to Dashboard to see changes.')
        } catch (e) {
            console.error(e)
            alert('Failed to generate data. Check console.')
        } finally {
            setLoading(false)
        }
    }

    const handleDeleteData = async () => {
        const confirmed = window.confirm(
            '⚠️ WARNING: This will DELETE ALL DATA in the database!\n\n' +
            'This includes:\n' +
            '• All Assets\n' +
            '• All Groups\n' +
            '• All Maintenance Tasks\n' +
            '• All Warranties\n' +
            '• All Service Contracts\n' +
            '• All Documents\n' +
            '• All Service Records\n\n' +
            'This action CANNOT be undone!\n\n' +
            'Are you absolutely sure?'
        )

        if (!confirmed) return

        // Double confirmation for safety
        const doubleConfirm = window.confirm(
            'Last chance! Are you 100% sure you want to delete ALL data?'
        )

        if (!doubleConfirm) return

        setDeleting(true)
        try {
            const result = await deleteAllData(client)
            alert(`✅ Success! ${result.message}`)
        } catch (e) {
            console.error(e)
            alert('❌ Failed to delete data. Check console for errors.')
        } finally {
            setDeleting(false)
        }
    }

    if (loading) {
        return (
            <Layout>
                <div className="loading-screen">
                    <div className="spinner" role="status"></div>
                </div>
            </Layout>
        )
    }

    return (
        <Layout>
            <div className="profile-page">
                <div className="container" style={{ maxWidth: '800px', margin: '0 auto' }}>
                    <motion.div
                        className="profile-container"
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                    >
                        <div className="glass-card profile-card">
                            {/* Profile Header */}
                            <div className="profile-header">
                                <div className="profile-avatar">
                                    <div className="avatar-circle">
                                        {(formData.displayName || user?.username || 'U').charAt(0).toUpperCase()}
                                    </div>
                                </div>

                                <div className="profile-info">
                                    <h1>{formData.displayName || user?.username || 'User'}</h1>
                                    <p className="profile-email">{user?.signInDetails?.loginId}</p>
                                    <span className="badge badge-success">Active</span>
                                </div>
                            </div>

                            {/* Profile Details */}
                            <div className="profile-details">
                                {editing ? (
                                    <div className="profile-form">
                                        <div className="input-group">
                                            <label className="input-label">Display Name</label>
                                            <input
                                                className="input-field"
                                                type="text"
                                                value={formData.displayName}
                                                onChange={(e) => setFormData({ ...formData, displayName: e.target.value })}
                                                placeholder="Enter your display name"
                                            />
                                        </div>

                                        <div className="input-group">
                                            <label className="input-label">Bio</label>
                                            <textarea
                                                className="input-field"
                                                value={formData.bio}
                                                onChange={(e) => setFormData({ ...formData, bio: e.target.value })}
                                                rows={4}
                                                placeholder="Tell us about yourself"
                                            />
                                        </div>

                                        <div className="profile-actions">
                                            <button className="btn btn-secondary" onClick={() => setEditing(false)}>
                                                Cancel
                                            </button>
                                            <button className="btn btn-primary" onClick={handleSave}>
                                                Save Changes
                                            </button>
                                        </div>
                                    </div>
                                ) : (
                                    <div className="profile-view">
                                        <div className="profile-field">
                                            <label>Bio</label>
                                            <p>{formData.bio || 'No bio provided yet.'}</p>
                                        </div>

                                        <button className="btn btn-primary" onClick={() => setEditing(true)}>
                                            Edit Profile
                                        </button>
                                    </div>
                                )}
                            </div>
                        </div>

                        {/* Developer Tools Section */}
                        <div className="glass-card stat-card" style={{ marginTop: '2rem', padding: '1.5rem' }}>
                            <div>
                                <h3>Developer Tools</h3>
                                <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', marginBottom: '1.5rem' }}>
                                    Utilities for testing and development.
                                </p>
                            </div>

                            <div style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap' }}>
                                <button
                                    className="btn btn-warning"
                                    onClick={handleSeedData}
                                    disabled={loading || deleting}
                                    style={{ flex: '1', minWidth: '200px' }}
                                >
                                    {loading ? 'Generating...' : '🛠️ Generate Sample Data'}
                                </button>

                                <button
                                    className="btn"
                                    onClick={handleDeleteData}
                                    disabled={loading || deleting}
                                    style={{
                                        flex: '1',
                                        minWidth: '200px',
                                        background: 'linear-gradient(135deg, #ff4444, #cc0000)',
                                        color: 'white',
                                        border: 'none'
                                    }}
                                >
                                    {deleting ? 'Deleting...' : '🗑️ Delete All Data'}
                                </button>
                            </div>

                            <div style={{
                                marginTop: '1rem',
                                padding: '0.75rem',
                                background: 'rgba(255, 68, 68, 0.1)',
                                borderRadius: '8px',
                                border: '1px solid rgba(255, 68, 68, 0.3)'
                            }}>
                                <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', margin: 0 }}>
                                    ⚠️ <strong>Warning:</strong> Delete All Data will permanently remove all records from the database. This action cannot be undone.
                                </p>
                            </div>
                        </div>
                    </motion.div>
                </div>
            </div>
        </Layout>
    )
}
