import { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import { generateClient } from 'aws-amplify/data'
import Navigation from '../components/Navigation'
import './ServiceTags.css'

// Schema will be generated by Amplify sandbox
const client = generateClient<any>()

export default function ServiceTags() {
    const [tags, setTags] = useState<any[]>([])
    const [loading, setLoading] = useState(true)
    const [showCreateModal, setShowCreateModal] = useState(false)
    const [filter, setFilter] = useState<string>('all')

    useEffect(() => {
        loadTags()
    }, [])

    const loadTags = async () => {
        try {
            const { data } = await client.models.ServiceTag.list({})
            setTags(data)
        } catch (error) {
            console.error('Error loading tags:', error)
        } finally {
            setLoading(false)
        }
    }

    const filteredTags = filter === 'all'
        ? tags
        : tags.filter(tag => tag.status === filter)

    if (loading) {
        return (
            <div className="loading-screen">
                <div className="spinner" role="status"></div>
            </div>
        )
    }

    return (
        <div className="service-tags-page">
            <Navigation />

            <div className="container">
                <motion.div
                    className="page-header"
                    initial={{ opacity: 0, y: -20 }}
                    animate={{ opacity: 1, y: 0 }}
                >
                    <div>
                        <h1>Service Tags</h1>
                        <p>Manage all your service tags in one place</p>
                    </div>
                    <button className="btn btn-primary" onClick={() => setShowCreateModal(true)}>
                        <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
                            <path d="M10 5V15M5 10H15" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
                        </svg>
                        New Tag
                    </button>
                </motion.div>

                {/* Filters */}
                <motion.div
                    className="filter-bar"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 0.2 }}
                >
                    <button
                        className={`filter-btn ${filter === 'all' ? 'active' : ''}`}
                        onClick={() => setFilter('all')}
                    >
                        All
                    </button>
                    <button
                        className={`filter-btn ${filter === 'active' ? 'active' : ''}`}
                        onClick={() => setFilter('active')}
                    >
                        Active
                    </button>
                    <button
                        className={`filter-btn ${filter === 'pending' ? 'active' : ''}`}
                        onClick={() => setFilter('pending')}
                    >
                        Pending
                    </button>
                    <button
                        className={`filter-btn ${filter === 'completed' ? 'active' : ''}`}
                        onClick={() => setFilter('completed')}
                    >
                        Completed
                    </button>
                </motion.div>

                {/* Tags Grid */}
                <div className="tags-grid">
                    {filteredTags.length > 0 ? (
                        filteredTags.map((tag, index) => (
                            <TagCard key={tag.id} tag={tag} delay={0.3 + index * 0.1} />
                        ))
                    ) : (
                        <motion.div
                            className="empty-state"
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 1 }}
                        >
                            <div className="empty-icon">📋</div>
                            <h3>No tags found</h3>
                            <p>Create your first service tag to get started!</p>
                            <button className="btn btn-primary mt-lg" onClick={() => setShowCreateModal(true)}>
                                Create Tag
                            </button>
                        </motion.div>
                    )}
                </div>
            </div>

            {showCreateModal && (
                <CreateTagModal onClose={() => setShowCreateModal(false)} onCreated={loadTags} />
            )}
        </div>
    )
}

interface TagCardProps {
    tag: any
    delay: number
}

function TagCard({ tag, delay }: TagCardProps) {
    const statusColors: Record<string, string> = {
        active: 'success',
        pending: 'warning',
        completed: 'primary',
        archived: 'tertiary',
    }

    const priorityIcons: Record<string, string> = {
        low: '🟢',
        medium: '🟡',
        high: '🟠',
        urgent: '🔴',
    }

    return (
        <motion.div
            className="glass-card tag-card"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay }}
            whileHover={{ scale: 1.02 }}
        >
            <div className="tag-header">
                <h3>{tag.title}</h3>
                <span className={`badge badge-${statusColors[tag.status || 'active']}`}>
                    {tag.status || 'active'}
                </span>
            </div>

            <p className="tag-description">{tag.description || 'No description provided'}</p>

            <div className="tag-meta">
                {tag.priority && (
                    <div className="tag-priority">
                        <span>{priorityIcons[tag.priority]}</span>
                        <span>{tag.priority}</span>
                    </div>
                )}
                {tag.category && (
                    <div className="tag-category">
                        <span>📁</span>
                        <span>{tag.category}</span>
                    </div>
                )}
            </div>

            {tag.dueDate && (
                <div className="tag-due-date">
                    <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                        <path d="M12 2.66667H4C3.26362 2.66667 2.66667 3.26362 2.66667 4V12C2.66667 12.7364 3.26362 13.3333 4 13.3333H12C12.7364 13.3333 13.3333 12.7364 13.3333 12V4C13.3333 3.26362 12.7364 2.66667 12 2.66667Z" stroke="currentColor" strokeWidth="1.5" />
                        <path d="M10.6667 1.33333V4M5.33333 1.33333V4M2.66667 6.66667H13.3333" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
                    </svg>
                    <span>{new Date(tag.dueDate).toLocaleDateString()}</span>
                </div>
            )}
        </motion.div>
    )
}

interface CreateTagModalProps {
    onClose: () => void
    onCreated: () => void
}

function CreateTagModal({ onClose, onCreated }: CreateTagModalProps) {
    const [formData, setFormData] = useState({
        title: '',
        description: '',
        category: '',
        status: 'pending',
        priority: 'medium',
    })
    const [creating, setCreating] = useState(false)

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault()
        setCreating(true)

        try {
            await client.models.ServiceTag.create(formData)
            onCreated()
            onClose()
        } catch (error) {
            console.error('Error creating tag:', error)
        } finally {
            setCreating(false)
        }
    }

    return (
        <motion.div
            className="modal-overlay"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            onClick={onClose}
        >
            <motion.div
                className="modal-content glass-card"
                initial={{ scale: 0.9, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                onClick={(e) => e.stopPropagation()}
            >
                <h2>Create New Service Tag</h2>

                <form onSubmit={handleSubmit}>
                    <div className="input-group">
                        <label className="input-label">Title</label>
                        <input
                            className="input-field"
                            type="text"
                            value={formData.title}
                            onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                            required
                            placeholder="Enter tag title"
                        />
                    </div>

                    <div className="input-group">
                        <label className="input-label">Description</label>
                        <textarea
                            className="input-field"
                            value={formData.description}
                            onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                            rows={3}
                            placeholder="Enter tag description"
                        />
                    </div>

                    <div className="input-group">
                        <label className="input-label">Category</label>
                        <input
                            className="input-field"
                            type="text"
                            value={formData.category}
                            onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                            placeholder="e.g., Development, Design"
                        />
                    </div>

                    <div className="form-row">
                        <div className="input-group">
                            <label className="input-label">Priority</label>
                            <select
                                className="input-field"
                                value={formData.priority}
                                onChange={(e) => setFormData({ ...formData, priority: e.target.value })}
                            >
                                <option value="low">Low</option>
                                <option value="medium">Medium</option>
                                <option value="high">High</option>
                                <option value="urgent">Urgent</option>
                            </select>
                        </div>

                        <div className="input-group">
                            <label className="input-label">Status</label>
                            <select
                                className="input-field"
                                value={formData.status}
                                onChange={(e) => setFormData({ ...formData, status: e.target.value })}
                            >
                                <option value="pending">Pending</option>
                                <option value="active">Active</option>
                                <option value="completed">Completed</option>
                            </select>
                        </div>
                    </div>

                    <div className="modal-actions">
                        <button type="button" className="btn btn-secondary" onClick={onClose}>
                            Cancel
                        </button>
                        <button type="submit" className="btn btn-primary" disabled={creating}>
                            {creating ? 'Creating...' : 'Create Tag'}
                        </button>
                    </div>
                </form>
            </motion.div>
        </motion.div>
    )
}
